### ISSUE TITLE
Problems filtering tasks containing notes

### ISSUE THREAD

**Issue by victoraraujo01** [bevesce/TodoFlow#10]
First of all, congratulations on this project! I've recently started keeping track of my tasks using the Taskpaper format and I think TodoFlow can help me a lot!

I'm currently facing some issues when I try to filter my tasks based on the `@done` tag. Here are some examples so the issue can be easily reproduced. Suppose I have a file like this:

    Project:
        - Task 1
            Note for task 1
        - Task 2 @done(2015-06-09)
            Note for task 2
        - Task 3 (without notes) @done(2015-06-09)

If I try to filter for `@done` tasks, I get the following result. The note for Task 2 is not included (I actually don't know if this is intended behavior, maybe this could be clarified?)

    >>> print(todos.filter('@done'))
    Project:
        - Task 2 @done(2015-06-09)
        - Task 3 (without notes) @done(2015-06-09)

Also, and this is actually my main issue, if I try to filter for tasks `not @done`, TodoFlow also returns `@done` tasks that have notes:

    >>> print(todos.filter('not @done'))
    Project:
        - Task 1
            Note for task 1
        - Task 2 @done(2015-06-09)
            Note for task 2

Does anyone else have these issues?

**Comment by bevesce** [comment]
Both cases work as intended.

You have a point that makes so-so sense, but original Taskpaper.app is the point of reference and it does the same.

To understand why it works like this you need to understand that:

1. there is very little difference between notes and tasks in taskpaper when it comes to search and filtering
2. parents of items that match the query are also in filtered list, even if they don't match the query themselves.

Working with your example, when you filter with `@done`:

```
Project: {doesn't match @done}
    - Task 1 {doesn't match @done}
        Note for task 1 {doesn't match @done}
    - Task 2 @done(2015-06-09) {matches @done}
        Note for task 2 {doesn't match @done}
    - Task 3 (without notes) @done(2015-06-09) {matches @done}
```

so it produces:

```
Project: {doesn't match  @done, but it's included here because some of the children do}
    - Task 2 @done(2015-06-09) {matches @done}
    - Task 3 (without notes) @done(2015-06-09) {matches @done}
```

Similary when with `not @done` it goes like this:

```
Project: {matches @done}
    - Task 1 {matches not @done}
        Note for task 1 {matches not @done}
    - Task 2 @done(2015-06-09) {doesn't match not @done}
        Note for task 2 {matches not @done}
    - Task 3 (without notes) @done(2015-06-09) {doesn't match not @done}
```

and it produces:

```
Project: {matches @done}
    - Task 1 {matches @done}
        Note for task 1 {matches @done}
    - Task 2 @done(2015-06-09) {doesn't match not @done, but it's included here because it's child does}
        Note for task 2 {matches @done}
```

Probably you can tweak your queries to achieve what you want, for example:

```
>>> print q.filter('@done +d')
Project:
    - Task 2 @done(2015-06-09)
        Note for task 2
    - Task 3 (without notes) @done(2015-06-09)
```

and

```
>>> print q.filter('not @done and type = task')
Project:
    - Task 1
```

**Comment by victoraraujo01** [comment]
Thanks for taking the time to explain. I'm actually on a Windows PC and don't have access to Taskpaper, so I've been managing my tasks on Sublime Text and thought maybe I would try to use TodoFlow to do some queries on them.

By the way, I've been experimenting with the ```+d``` parameter and noticed it didn't work on the following case:

    >>> print(t.filter('not @done and type = task +d'))
    Syntax error in input!
    LexToken(PLUS_DESCENDANTS,'+d',1,26)
    Project:
        - Task 1
            Note for task 1
        - Task 2 @done(2015-06-09)
            Note for task 2
        - Task 3 (without notes) @done(2015-06-09)

Thanks for your help!

**Comment by bevesce** [comment]
That is a bug, I'll try to fix it in some free time

**Comment by bevesce** [comment]
It should work now
