### ISSUE TITLE
Support for Pythonista/Editorial

### ISSUE THREAD

**Issue by hendrikstier** [bevesce/TodoFlow#13]
Would it be possible to include this functionality again? I'd be glad to help, but need pointers on the issues, Currently I'm encountering issues in [parser.py.37](https://github.com/bevesce/TodoFlow/blob/master/todoflow/parser.py#L37) stating an Attribute Error with NoneTypes when trying to parse a simple String via

    todoflow.from_text("""
      Topic
        - Task 1
    """)

**Comment by bevesce** [comment]
I'll look into this. Can you tell me how do you install python modules in Editorial?

**Comment by hendrikstier** [comment]
Thank you! I used the script from https://github.com/jsbain/GitHubGet to retrieve ToDoFlow and ply from GitHub, storing both libraries in subdirectories "ply" resp. "todoflow" within Pythonista.

**Comment by bevesce** [comment]
Idk, I downloaded both scripts with the one linked by you, I moved folders to site-packages in Pythonista and it worked for me. Can you include stack trace or something?

**Comment by bevesce** [comment]
You can also check this workflow in Editorial http://www.editorial-workflows.com/workflow/5774273822064640/VvWXdUHEMPQ but I didn't use it for some time and I'm not sure if it's still working
