### ISSUE TITLE
Please fix parentheses escaping in tag values

### ISSUE THREAD

**Issue by saf-dmitry** [bevesce/TodoFlow#17]
Since [release 3.2](https://www.taskpaper.com/releases/) TaskPaper app requires both `(` and `)` to be escaped with `\` when used in tag values.

**Comment by bevesce** [comment]
Can you give me couple of examples when this breaks things? I'm trying to write some tests but nothing comes to my mind.

**Comment by saf-dmitry** [comment]
In general, all the saved searches in document, which include parentheses as part of search query, i.e.:

    @search(@today and not \(@done or @hold\))

**Comment by bevesce** [comment]
It should work now. Thanks
